stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
    - cp public/_redirects dist/
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - npx netlify-cli deploy --dir=dist --prod
  environment:
    name: production
  only:
    - main
